# Clinical Data Analysis

This project analyzes hospital patient data to identify cost patterns, patient trends, and healthcare insights.

## Data Loading

In [1]:
import pandas as pd

df = pd.read_csv("clinical_data.csv")

## Data Understanding

In [6]:
df.shape

(984, 10)

In [8]:
df.columns

Index(['Patient_ID', 'Age', 'Gender', 'Condition', 'Procedure', 'Cost',
       'Length_of_Stay', 'Readmission', 'Outcome', 'Satisfaction'],
      dtype='object')

In [12]:
df.head()

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
0,1,45,Female,Heart Disease,Angioplasty,15000,5,No,Recovered,4
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3
2,3,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,Recovered,5
3,4,75,Male,Stroke,CT Scan and Medication,10000,7,Yes,Stable,2
4,5,50,Female,Cancer,Surgery and Chemotherapy,25000,10,No,Recovered,4

In [14]:
df.tail()

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
979,996,68,Male,Hypertension,Medication and Counseling,1000,70,No,Stable,4
980,997,45,Female,Appendicitis,Appendectomy,8000,72,No,Recovered,3
981,998,40,Male,Fractured Leg,Cast and Physical Therapy,3000,72,No,Recovered,4
982,999,78,Female,Heart Attack,Cardiac Catheterization,18000,74,Yes,Stable,2
983,1000,25,Male,Allergic Reaction,Epinephrine Injection,100,68,No,Recovered,5

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient_ID      984 non-null    int64
 1   Age             984 non-null    int64
 2   Gender          984 non-null    object
 3   Condition       984 non-null    object
 4   Procedure       984 non-null    object
 5   Cost            984 non-null    int64
 6   Length_of_Stay  984 non-null    int64
 7   Readmission     984 non-null    object
 8   Outcome         984 non-null    object
 9   Satisfaction    984 non-null    int64
dtypes: int64(5), object(5)
memory usage: 77.0+ KB

In [9]:
df.describe()

        Patient_ID         Age          Cost  Length_of_Stay  Satisfaction
count   984.000000  984.000000    984.000000      984.000000    984.000000
mean    500.329268   53.754065   8367.479675       37.663618      3.598577
std     288.979531   14.941135   7761.990976       19.595805      0.883002
min       1.000000   25.000000    100.000000        1.000000      2.000000
25%     250.750000   45.000000   1000.000000       21.000000      3.000000
50%     500.500000   55.000000   6000.000000       38.000000      4.000000
75%     750.250000   65.000000  15000.000000       54.250000      4.000000
max    1000.000000   78.000000  25000.000000       76.000000      5.000000

- Dataset contains patient details including age, gender, condition, cost, and outcomes
- Explored structure and summary statistics

## Data Cleaning

In [26]:
df.isnull().sum()

Patient_ID        0
Age               0
Gender            0
Condition         0
Procedure         0
Cost              0
Length_of_Stay    0
Readmission       0
Outcome           0
Satisfaction      0
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(0)

- Checked for missing values → none found
- Checked for duplicates → none found
- Dataset is clean and ready for analysis

## Data Analysis

### 1. Patient Distribution by Condition

This analysis shows the number of patients affected by each medical condition.

In [102]:
df.groupby("Condition")["Patient_ID"].count()

Condition
Allergic Reaction        66
Appendicitis             66
Cancer                   66
Childbirth               65
Diabetes                 65
Fractured Arm            66
Fractured Leg            67
Heart Attack             67
Heart Disease            65
Hypertension             66
Kidney Stones            65
Osteoarthritis           64
Prostate Cancer          65
Respiratory Infection    65
Stroke                   66
Name: Patient_ID, dtype: int64

- Patient distribution across conditions is nearly uniform, with multiple conditions having the same highest count. 
This indicates no single condition dominates the dataset.

### 2. Patient Distribution by Gender
This analysis shows the distribution of patients by gender.

In [105]:
df.groupby("Gender")["Age"].count()

Gender
Female    524
Male      460
Name: Age, dtype: int64

- Female patients are slightly higher compared to female patients, indicating a marginally higher hospital admission rate among females.

### 3. Average Treatment Cost by Condition

This analysis helps identify which medical conditions have higher treatment costs.

In [44]:
df.groupby("Condition")["Cost"].mean().sort_values(ascending = False)

Condition
Cancer                   25000.0
Prostate Cancer          20000.0
Heart Attack             18000.0
Heart Disease            15000.0
Childbirth               12000.0
Stroke                   10000.0
Appendicitis              8000.0
Kidney Stones             6000.0
Osteoarthritis            4000.0
Fractured Leg             3000.0
Diabetes                  2000.0
Hypertension              1000.0
Respiratory Infection      800.0
Fractured Arm              500.0
Allergic Reaction          100.0
Name: Cost, dtype: float64

- Cancer has the highest average treatment cost, followed by prostate cancer. 
This indicates that these conditions contribute to higher financial burden on patients and healthcare systems.

### 4. Average Length of Stay by Condition
This analysis shows ehich condtions require longer hospitalization.

In [99]:
df.groupby("Condition")["Length_of_Stay"].mean().sort_values(ascending = False)

Condition
Cancer                   42.651515
Prostate Cancer          41.584615
Heart Attack             41.000000
Stroke                   40.333333
Fractured Leg            39.000000
Heart Disease            38.215385
Osteoarthritis           37.859375
Appendicitis             37.439394
Kidney Stones            36.461538
Diabetes                 36.092308
Childbirth               35.523077
Hypertension             35.515152
Respiratory Infection    34.661538
Fractured Arm            34.257576
Allergic Reaction        34.242424
Name: Length_of_Stay, dtype: float64

- Cancer patients have the highest average length of stay, indicating longer hospitalization requirements and higher resource utilization, helping hospitals plan bed occupancy.

### 5. Patient Satisfaction Analysis
This analysis shows how satisfied patients are with their treatment and hospital services.

In [104]:
df.groupby("Satisfaction")["Condition"].count()

Satisfaction
2    133
3    261
4    458
5    132
Name: Condition, dtype: int64

- Most patients fall under satisfaction level 4, indicating generally positive patient experience across conditions, with minimal variation between conditions.

### 6. Patient Outcome Analysis
This analysis shows treatment effectiveness based on patient outcomes.

In [96]:
df.groupby("Outcome")["Patient_ID"].count()

Outcome
Recovered    591
Stable       393
Name: Patient_ID, dtype: int64

- A higher number of patients have recovered compared to other outcomes,indicating overall treatment effectiveness.

## Final Summary

This project analyzed hospital patient data to understand treatment costs, patient distribution, hospital stay duration, satisfaction levels, and outcomes.

Key findings include:
- Patient distribution is balanced across conditions
- Cancer has the highest treatment cost and longest hospital stay
- Female patients are slightly higher than male patients
- Most patients report good satisfaction levels
- Recovery rate is high, indicating effective treatments

Overall, the analysis provides insights into healthcare trends and resource utilization, which can help hospitals improve decision-making and patient care.